---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
- name: centos-6
  driver_config:
    image: centos:centos6
    platform: centos
- name: ubuntu-14.04

suites:
  - name: default
    run_list: nmd-skeletor::default
