language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
install: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && script/cached-bundle install --without integration --deployment || bundle install --without integration --deployment'
notifications:
  hipchat:
    rooms:
      secure:
script: bundle exec rake test
env:
  global:
    secure:
